//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ann_shop_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySaveNotification
    {
        public string GhtkCode { get; set; }
        public int OrderId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> ReasonCode { get; set; }
        public string Reason { get; set; }
        public double Weight { get; set; }
        public decimal GhtkFee { get; set; }
        public Nullable<decimal> GhtkCod { get; set; }
        public int ReturnPartPackage { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> Cod { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string Staff { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual DeliverySaveReason DeliverySaveReason { get; set; }
        public virtual DeliverySaveStatu DeliverySaveStatu { get; set; }
        public virtual tbl_Order tbl_Order { get; set; }
    }
}
