//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ann_shop_server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public System.Guid UUID { get; set; }
        public string SecretKey { get; set; }
        public int UserID { get; set; }
        public string Browser { get; set; }
        public string Device { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastDate { get; set; }
    }
}
